### ISSUE TITLE
PRs not merging

### ISSUE THREAD

**Issue by mikedparrott** [conda-forge/aimodelshare-feedstock#11]
### Comment:

@conda-forge-admin Our pull requests are not merging automatically.  Our maintainers do not have the ability to merge pull requests b/c they do not have write access.  Please advise.

**Comment by hmaarrfk** [comment]
did you ever accept the invite?

**Comment by hmaarrfk** [comment]
I believe your invitation is still pending. 

can you check your email or try to go to
https://github.com/conda-forge

**Comment by mikedparrott** [comment]
Merging works now!  Thanks Mark!
